import 'package:flutter/material.dart';

ColorScheme get colorSchemePers {
  return const ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xff555a92),
    surfaceTint: Color(0xff555a92),
    onPrimary: Color(0xffffffff),
    primaryContainer: Color(0xffe0e0ff),
    onPrimaryContainer: Color(0xff3d4279),
    secondary: Color(0xff5c5d72),
    onSecondary: Color(0xffffffff),
    secondaryContainer: Color(0xffe1e0f9),
    onSecondaryContainer: Color(0xff444559),
    tertiary: Color(0xff78536b),
    onTertiary: Color(0xffffffff),
    tertiaryContainer: Color(0xffffd8ee),
    onTertiaryContainer: Color(0xff5e3c53),
    error: Color(0xffba1a1a),
    onError: Color(0xffffffff),
    errorContainer: Color(0xffffdad6),
    onErrorContainer: Color(0xff93000a),
    surface: Color(0xfffbf8ff),
    onSurface: Color(0xff1b1b21),
    onSurfaceVariant: Color(0xff46464f),
    outline: Color(0xff777680),
    outlineVariant: Color(0xffc7c5d0),
    shadow: Color(0xff000000),
    scrim: Color(0xff000000),
    inverseSurface: Color(0xff303036),
    inversePrimary: Color(0xffbec2ff),
    primaryFixed: Color(0xffe0e0ff),
    onPrimaryFixed: Color(0xff10144b),
    primaryFixedDim: Color(0xffbec2ff),
    onPrimaryFixedVariant: Color(0xff3d4279),
    secondaryFixed: Color(0xffe1e0f9),
    onSecondaryFixed: Color(0xff191a2c),
    secondaryFixedDim: Color(0xffc5c4dd),
    onSecondaryFixedVariant: Color(0xff444559),
    tertiaryFixed: Color(0xffffd8ee),
    onTertiaryFixed: Color(0xff2e1126),
    tertiaryFixedDim: Color(0xffe7b9d5),
    onTertiaryFixedVariant: Color(0xff5e3c53),
    surfaceDim: Color(0xffdbd9e0),
    surfaceBright: Color(0xfffbf8ff),
    surfaceContainerLowest: Color(0xffffffff),
    surfaceContainerLow: Color(0xfff5f2fa),
    surfaceContainer: Color(0xfff0ecf4),
    surfaceContainerHigh: Color(0xffeae7ef),
    surfaceContainerHighest: Color(0xffe4e1e9),
  );
}
